module.exports = [
    {"dispName": "Skorpyron", "name": "skorpyron",
        "model": {
            patchwerk_ba_2t: 0,
            patchwerk_ba_st: 0,
            patchwerk_sa_2t: 0.1,
            patchwerk_sa_st: 0.1,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0,
            lowmovement_ba_2t: 0,
            lowmovement_ba_st: 0,
            lowmovement_sa_2t: 0,
            lowmovement_sa_st: 0.55,
            lowmovement_na_2t: 0.25,
            lowmovement_na_st: 0,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0,
            highmovement_sa_2t: 0,
            highmovement_sa_st: 0,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "Chronomatic Anomaly", "name": "anomaly",
        "model": {
            patchwerk_ba_2t: 0,
            patchwerk_ba_st: 0,
            patchwerk_sa_2t: 0,
            patchwerk_sa_st: 0,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0,
            lowmovement_ba_2t: 0,
            lowmovement_ba_st: 0.2,
            lowmovement_sa_2t: 0,
            lowmovement_sa_st: 0,
            lowmovement_na_2t: 0,
            lowmovement_na_st: 0,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0.8,
            highmovement_sa_2t: 0,
            highmovement_sa_st: 0,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "Trilliax", "name": "trilliax",
        "model": {
            patchwerk_ba_2t: 0,
            patchwerk_ba_st: 0.3,
            patchwerk_sa_2t: 0,
            patchwerk_sa_st: 0,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0,
            lowmovement_ba_2t: 0,
            lowmovement_ba_st: 0.7,
            lowmovement_sa_2t: 0,
            lowmovement_sa_st: 0,
            lowmovement_na_2t: 0,
            lowmovement_na_st: 0,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0,
            highmovement_sa_2t: 0,
            highmovement_sa_st: 0,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "Spellblade Aluriel", "name": "aluriel",
        "model": {
            patchwerk_ba_2t: 0.1,
            patchwerk_ba_st: 0.25,
            patchwerk_sa_2t: 0,
            patchwerk_sa_st: 0,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0,
            lowmovement_ba_2t: 0.65,
            lowmovement_ba_st: 0,
            lowmovement_sa_2t: 0,
            lowmovement_sa_st: 0,
            lowmovement_na_2t: 0,
            lowmovement_na_st: 0,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0,
            highmovement_sa_2t: 0,
            highmovement_sa_st: 0,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "Tichondrius", "name": "tichondrius",
        "model": {
            patchwerk_ba_2t: 0,
            patchwerk_ba_st: 0,
            patchwerk_sa_2t: 0,
            patchwerk_sa_st: 0,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0,
            lowmovement_ba_2t: 0,
            lowmovement_ba_st: 0,
            lowmovement_sa_2t: 0,
            lowmovement_sa_st: 0.65,
            lowmovement_na_2t: 0,
            lowmovement_na_st: 0,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0,
            highmovement_sa_2t: 0,
            highmovement_sa_st: 0.35,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "High Botanist Tel'arn", "name": "botanist",
        "model": {
            patchwerk_ba_2t: 0,
            patchwerk_ba_st: 0,
            patchwerk_sa_2t: 0,
            patchwerk_sa_st: 0,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0,
            lowmovement_ba_2t: 0.6,
            lowmovement_ba_st: 0,
            lowmovement_sa_2t: 0.25,
            lowmovement_sa_st: 0,
            lowmovement_na_2t: 0,
            lowmovement_na_st: 0,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0,
            highmovement_sa_2t: 0.15,
            highmovement_sa_st: 0,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "Star Augur Etraeus", "name": "augur",
        "model": {
            patchwerk_ba_2t: 0,
            patchwerk_ba_st: 0,
            patchwerk_sa_2t: 0,
            patchwerk_sa_st: 0,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0,
            lowmovement_ba_2t: 0,
            lowmovement_ba_st: 0.35,
            lowmovement_sa_2t: 0,
            lowmovement_sa_st: 0,
            lowmovement_na_2t: 0,
            lowmovement_na_st: 0.65,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0,
            highmovement_sa_2t: 0,
            highmovement_sa_st: 0,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "Krosus", "name": "krosus",
        "model": {
            patchwerk_ba_2t: 0,
            patchwerk_ba_st: 0,
            patchwerk_sa_2t: 0,
            patchwerk_sa_st: 0.4,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0.6,
            lowmovement_ba_2t: 0,
            lowmovement_ba_st: 0,
            lowmovement_sa_2t: 0,
            lowmovement_sa_st: 0,
            lowmovement_na_2t: 0,
            lowmovement_na_st: 0,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0,
            highmovement_sa_2t: 0,
            highmovement_sa_st: 0,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "Grand Magistrix Elisande", "name": "elisande",
        "model": {
            patchwerk_ba_2t: 0,
            patchwerk_ba_st: 0,
            patchwerk_sa_2t: 0,
            patchwerk_sa_st: 0,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0,
            lowmovement_ba_2t: 0.3,
            lowmovement_ba_st: 0.6,
            lowmovement_sa_2t: 0,
            lowmovement_sa_st: 0,
            lowmovement_na_2t: 0.1,
            lowmovement_na_st: 0,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0,
            highmovement_sa_2t: 0,
            highmovement_sa_st: 0,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "Gul'dan", "name": "guldan",
        "model": {
            patchwerk_ba_2t: 0.15,
            patchwerk_ba_st: 0.15,
            patchwerk_sa_2t: 0.1,
            patchwerk_sa_st: 0.2,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0.1,
            lowmovement_ba_2t: 0,
            lowmovement_ba_st: 0.1,
            lowmovement_sa_2t: 0,
            lowmovement_sa_st: 0,
            lowmovement_na_2t: 0.2,
            lowmovement_na_st: 0,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0,
            highmovement_sa_2t: 0,
            highmovement_sa_st: 0,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    },
    {"dispName": "Nighthold Composite", "name": "nighthold",
        "model": {
            patchwerk_ba_2t: 0.025,
            patchwerk_ba_st: 0.07,
            patchwerk_sa_2t: 0.02,
            patchwerk_sa_st: 0.07,
            patchwerk_na_2t: 0,
            patchwerk_na_st: 0.07,
            lowmovement_ba_2t: 0.155,
            lowmovement_ba_st: 0.195,
            lowmovement_sa_2t: 0.05,
            lowmovement_sa_st: 0.12,
            lowmovement_na_2t: 0.03,
            lowmovement_na_st: 0.065,
            highmovement_ba_2t: 0,
            highmovement_ba_st: 0.08,
            highmovement_sa_2t: 0.015,
            highmovement_sa_st: 0.035,
            highmovement_na_2t: 0,
            highmovement_na_st: 0
        }
    }
]